---
- hosts: sparknodes
  vars:
    master: "{{ MASTER_YES }}"
    spark_url: "{{ SPARK_URL }}"
    user: "{{ USER }}"
    master_ip: "{{ MASTER_IP }}"
  user: "{{user}}"

  tasks:
   - name: Run apt-get update
     apt: update_cache=yes

   - name: Install wget
     apt: pkg=wget state=installed update_cache=true

   - name: create spark dir
     file: path=/spark state=directory mode=0755

   - name: download sources
     sudo: true
     get_url: url=http://ftp.wayne.edu/apache/spark/spark-1.6.2/spark-1.6.2-bin-hadoop2.6.tgz dest=/spark/

   - name: Unarchive Spark download
     sudo: true
     unarchive: src=/spark/spark-1.6.2-bin-hadoop2.6.tgz dest=/spark copy=no

   - name: Move spark dir to spark_latest
     sudo: true
     command: mv /spark/spark-1.6.2-bin-hadoop2.6 /spark/spark_latest

   - name: Install JRE to set JAVA_HOME
     sudo: true
     apt: name=openjdk-7-jre state=present

   - name: Start Spark Master
     environment:
         SPARK_LOCAL_IP: "{{master_ip}}"
         SPARK_MASTER_IP: "{{master_ip}}"
     sudo: true
     when: master=="true"
     command: sh /spark/spark_latest/sbin/start-master.sh -h {{master_ip}}
     tags:
         - startmaster

   - name: Stop Slaves
     sudo: true
     when: master=="false"
     command: /spark/spark_latest/sbin/stop-slave.sh
     tags: 
         - stop

   - name: Start Spark Slaves
     sudo: true
     when: master=="false"
     command: /spark/spark_latest/sbin/start-slave.sh {{spark_url}} -h {{ ansible_eth0["ipv4"]["address"] }}
     tags:
         - start
